app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('request.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/request/urls.py
from django.urls import path
from request.views import LandingPageView, RequestIndexView, SuccessView, ActivationDetailView, ActivationListView

app_name = "request"

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing_page'),
    path('request/', RequestIndexView.as_view(), name='index'),
    path('success/', SuccessView.as_view(), name='success'),
    path('activation/', ActivationListView.as_view(), name="activation-list"),
    path('activation/<int:pk>/', ActivationDetailView.as_view(), name='activation-detail'),
]

app/request/forms.py
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Row, Div, ButtonHolder, Submit
from django_cf_turnstile.fields import TurnstileCaptchaField
from django import forms
from django.forms import ModelForm
from .models import Request, CloudflareZone, AppSettings


def _password_field():
    return forms.TextInput(attrs={"type": "password", "autocomplete": "current-password"})


class AppSettingsForm(ModelForm):
    class Meta:
        model = Request
        fields = '__all__'
        widgets = {
            "upcloud_api_password": _password_field(),
            "cloudflare_api_token": _password_field(),
            "cloudflare_turnstile_secret": _password_field(),
            "mailjet_api_secret": _password_field()
        }


class RequestForm(ModelForm):
    class Meta:
        model = Request
        fields = ['party_name', 'party_url', 'contact_email', 'party_start', 'party_end', 'domain', 'cloudflare_zone',
                  'inception_date', 'extra_info', 'captcha']

    cloudflare_zone = forms.ModelChoiceField(empty_label=None, queryset=None)

    _app_settings = AppSettings.load()
    captcha = TurnstileCaptchaField(
        site_key=_app_settings.cloudflare_turnstile_key,
        secret_key=_app_settings.cloudflare_turnstile_secret,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['extra_info'].widget.attrs = {'rows': 3}

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Div('party_name', css_class='form-group col-md-6 mb-0'),
                Div('party_url', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Div('contact_email', css_class='form-group col-md-6 mb-0'),

                css_class='form-row'
            ),
            Row(
                Div('party_start', css_class='form-group col-md-6 mb-0'),
                Div('party_end', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Div('domain', css_class='form-group col-md-6 mb-0'),
                Div('cloudflare_zone', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Div('inception_date', css_class='form-group col-md-6 mb-0'),
                Div('extra_info', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Div('captcha', css_class='form-group col-md-6 mb-0')
            ),
            ButtonHolder(
                Submit('submit', 'Submit'),
            )
        )

        self.fields['cloudflare_zone'].queryset = CloudflareZone.objects.filter(public=True)
        self.fields['cloudflare_zone'].label = "Partyman host"


class ActivationForm(ModelForm):
    class Meta:
        model = Request
        fields = ['party_name', 'contact_email', 'domain', 'cloudflare_zone', 'upcloud_zone',
                  'upcloud_plan']

    def __init__(self, *args, **kwargs):
        self.approved = kwargs.pop('approved', False)
        self.deactivated = kwargs.pop('deactivated', False)
        super().__init__(*args, **kwargs)

        self.fields['upcloud_zone'].widget.attrs.update({"autocomplete": "off"})
        self.fields['upcloud_zone'].required = True
        self.fields['upcloud_plan'].widget.attrs.update({"autocomplete": "off"})
        self.fields['upcloud_plan'].required = True

        if self.approved:
            self.fields['domain'].disabled = True
            self.fields['cloudflare_zone'].disabled = True
            self.fields['upcloud_zone'].disabled = True
            self.fields['upcloud_plan'].disabled = True

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Div('party_name', css_class='form-group col-md-6 mb-0'),
                Div('contact_email', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Div('domain', css_class='form-group col-md-6 mb-0'),
                Div('cloudflare_zone', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Div('upcloud_zone', css_class='form-group col-md-6 mb-0'),
                Div('upcloud_plan', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            )
        )

app/request/views.py
from django.db.models import Avg, Case, DateTimeField, DurationField, ExpressionWrapper, F, Value, When, Count
from django.db.models.functions import Coalesce
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, ListView
from django.utils import timezone

from request.forms import RequestForm, ActivationForm
from request.helpers import get_cloudflare_dns_records, create_cloudflare_dns_entry, create_upcloud_server, \
    delete_cloudflare_dns_entry, stop_upcloud_server, delete_upcloud_server
from request.models import Request, PortfolioItem, AppSettings


class LandingPageView(ListView):
    template_name = "landingpage/index.html"
    model = PortfolioItem

    def get_queryset(self):
        return self.model.objects.filter(visible=True).order_by("sort_order")

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["timestamp"] = timezone.now()
        return ctx


class RequestIndexView(CreateView):
    template_name = "request/index.html"
    model = Request
    form_class = RequestForm
    success_url = reverse_lazy('request:success')


class SuccessView(TemplateView):
    template_name = "request/success.html"


class ActivationListView(ListView):
    template_name = "request/activation-list.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["zones"] = list(Request.objects
                            .values("upcloud_zone__name")
                            .filter(upcloud_zone__name__isnull=False)
                            .annotate(count=Count("upcloud_zone__name")).order_by("-count"))
        ctx["plans"] = list(Request.objects
                            .values("upcloud_plan__name")
                            .filter(upcloud_plan__name__isnull=False)
                            .annotate(count=Count("upcloud_plan__name")).order_by("-count"))
        ctx["average_duration_activated"] = (Request.objects.filter(activated__isnull=False, deactivated__isnull=False)
        .aggregate(
            avg_duration=Avg(
                ExpressionWrapper(F("deactivated") - F("activated"), output_field=DurationField())
            )
        )["avg_duration"])
        return ctx

    def get_queryset(self):
        return Request.objects.prefetch_related("activated_by", "deactivated_by", "upcloud_zone").annotate(
            is_inactive=Case(
                When(activated__isnull=False, deactivated__isnull=True, then=Value(0)),
                default=Value(1),
            ),
            duration_activated=Case(
                When(
                    activated__isnull=False,
                    then=ExpressionWrapper(
                        Coalesce(
                            "deactivated",
                            Value(timezone.now(), output_field=DateTimeField()),
                        ) - F("activated"),
                        output_field=DurationField(),
                    ),
                ),
                default=Value(None, output_field=DurationField()),
            )
        ).order_by("is_inactive", "-party_start")


class ActivationDetailView(UpdateView):
    template_name = "request/activation-detail.html"
    model = Request
    form_class = ActivationForm
    success_url = reverse_lazy('request:success')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'approved': self.get_object().is_approved})
        kwargs.update({'deactivated': bool(self.get_object().deactivated)})
        return kwargs

    def form_valid(self, form):
        settings = AppSettings.load()
        if "Deactivate" in self.request.POST["submit"]:
            request = self.get_object()
            form.instance.cloudflare_zone = request.cloudflare_zone
            form.instance.domain = request.domain
            form.instance.deactivated_by = self.request.user
            form.instance.deactivated = timezone.now()
            if not settings.sandbox_mode:
                stop_upcloud_server(form.instance)
                delete_cloudflare_dns_entry(form.instance.cloudflare_zone, form.instance.cloudflare_dns_record_id)
                delete_upcloud_server(form.instance)
            form.save()
            return HttpResponseRedirect(reverse_lazy("request:activation-list"))
        else:
            # print(type(form.instance), vars(form.instance))
            if not settings.sandbox_mode:
                domain = form.instance.domain + "." + form.instance.cloudflare_zone.name
                if domain in [record.name for record in get_cloudflare_dns_records(form.instance.cloudflare_zone)]:
                    form.add_error('domain', f"Domain {domain} already exists")
                    return self.form_invalid(form)

                server_id, server_address = create_upcloud_server(form.instance)
                if not server_id or not server_address:
                    form.add_error(None, "Failed to create UpCloud server")
                    return self.form_invalid(form)
                cf_dns_id = create_cloudflare_dns_entry(form.instance.cloudflare_zone, form.instance.domain,
                                                        server_address)
                form.instance.cloudflare_dns_record_id = cf_dns_id
            form.instance.is_approved = True
            form.instance.activated_by = self.request.user
            form.instance.activated = timezone.now()

        return super().form_valid(form)

app/request/templates/request/activation-detail.html
{% extends 'request/base.html' %}{% load crispy_forms_tags %}

{% block title %}Activate PartyMan Instance{% endblock %}

{% block content %}
    <h2>Activate PartyMan instance</h2>
    <form method="post">
        {% crispy form %}

        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#confirmModal">
            {% if object.activated %}
                Deactivate
            {% else %}
                Activate
            {% endif %}
        </button>

        <div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        You are about to
                        {% if object.activated %}
                            deactivate
                        {% else %}
                            activate
                        {% endif %}
                        this Request, are you sure?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>

                        {% if object.activated %}
                            <input type="submit" class="btn btn-primary" name="submit" value="Deactivate">
                        {% else %}
                            <input type="submit" class="btn btn-primary" name="submit" value="Activate">
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>

    </form>

{% endblock %}

app/request/templates/request/activation-list.html
{% extends 'request/base.html' %} {% load www-extras %}

{% block title %}Manage Partyman instances{% endblock %}

{% block extrahead %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@7.3.2/css/flag-icons.min.css"/>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.1/dist/chart.umd.min.js"
            integrity="sha256-SERKgtTty1vsDxll+qzd4Y2cF9swY9BCq62i9wXJ9Uo=" crossorigin="anonymous"></script>
    <script>
        document.addEventListener("DOMContentLoaded", ready)

        function ready() {

            const zoneLabels = [
                {% for zone in zones %}
                    "{{ zone.upcloud_zone__name|escapejs }}"{% if not forloop.last %},{% endif %}
                {% endfor %}
            ]
            const zoneCounts = [
                {% for zone in zones %}
                    {{ zone.count }}{% if not forloop.last %},{% endif %}
                {% endfor %}
            ]

            const planLabels = [
                {% for plan in plans %}
                    "{{ plan.upcloud_plan__name|escapejs }}"{% if not forloop.last %},{% endif %}
                {% endfor %}
            ]
            const planCounts = [
                {% for plan in plans %}
                    {{ plan.count }}{% if not forloop.last %},{% endif %}
                {% endfor %}
            ]

            const zoneData = {
                labels: zoneLabels,
                datasets: [{
                    label: "Instances by Zone",
                    data: zoneCounts,
                    backgroundColor: ["#64b5f6", "#42a5f5", "#2196f3", "#1e88e5", "#1976d2", "#1565c0", "#0d47a1"],
                    borderWidth: 0,
                    hoverBorderWidth: 0,
                    hoverOffset: 8
                }]
            }

            const planData = {
                labels: planLabels,
                datasets: [{
                    label: "Plans",
                    data: planCounts,
                    backgroundColor: ["#64b5f6", "#42a5f5", "#2196f3", "#1e88e5", "#1976d2", "#1565c0", "#0d47a1"],
                    borderWidth: 0,
                    hoverBorderWidth: 0,
                    hoverOffset: 8
                }]
            }

            const chartZoneUsageElem = document.getElementById("chartZoneUsage"),
                chartPlanUsageElem = document.getElementById("chartPlanUsage"),
                chartZoneUsage = new Chart(chartZoneUsageElem, {type: "doughnut", data: zoneData}),
                chartPlanUsage = new Chart(chartPlanUsageElem, {type: "doughnut", data: planData})
        }

    </script>

    <style>
        .smaller {
            font-size: 0.6em;
        }
    </style>
{% endblock %}

{% block content %}
    <h2>Manage Partyman instances</h2>

    <div class="row">
        <div class="col-12 col-md-9">
            <div class="table-responsive">
                <table class="table table-sm">
                    <thead>
                    <tr>
                        <th colspan="2">Name</th>
                        <th>Event info</th>
                        <th>Duration</th>
                        <th>Activated</th>
                        <th>Deactivated</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr class="align-middle">
                            <td>
                                <small>
                                    {% if object.party_url %}
                                        <a href="{{ object.party_url }}">{{ object.party_name }}</a>
                                    {% else %}
                                        {{ object.party_name }}
                                    {% endif %}
                                </small>
                            </td>
                            <td>
                                {% if not object.deactivated %}
                                    <a href="{% url 'request:activation-detail' object.pk %}"
                                       class="btn btn-primary btn-sm">Manage</a>
                                {% endif %}
                            </td>
                            <td>
                                <small>
                                    {{ object.party_start|date:"Y-m-d" }}<br>
                                    {% if object.upcloud_zone %}
                                        <span class="fi fi-{{ object.upcloud_zone.name|slice:"0:2" }}"></span>
                                    {% endif %}
                                    {{ object.upcloud_zone }}
                                </small>
                            </td>
                            <td>
                                <small>
                                    {% if not object.is_inactive %}
                                        <i class="fa-solid fa-person-running"></i>
                                    {% endif %}
                                    {{ object.duration_activated|duration_weeks_days_hours }}
                                </small>
                            </td>
                            <td>
                                {% if object.activated %}
                                    <small class="smaller">
                                        <i class="fa-regular fa-calendar-days me-1"></i>{{ object.activated|date:"Y-m-d" }}<br>
                                        <i class="fa-regular fa-clock me-1"></i>{{ object.activated|date:"H:i" }}
                                        {% if object.activated_by %}
                                            <br> <i class="fa-regular fa-user me-1"></i>{{ object.activated_by }}
                                        {% endif %}
                                    </small>
                                {% endif %}
                            </td>
                            <td>
                                {% if object.deactivated %}
                                    <small class="smaller">
                                        <i class="fa-regular fa-calendar-days me-1"></i>{{ object.deactivated|date:"Y-m-d" }}<br>
                                        <i class="fa-regular fa-clock me-1"></i>{{ object.deactivated|date:"H:i" }}
                                        {% if object.deactivated_by %}
                                            <br> <i class="fa-regular fa-user me-1"></i>{{ object.deactivated_by }}
                                        {% endif %}
                                    </small>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-12 col-md-3">
            <h6>Average duration</h6>
            {{ average_duration_activated|duration_weeks_days_hours }}
            <hr/>
            <h6>Zones by usage</h6>
            <canvas id="chartZoneUsage" class="mb-4"></canvas>
            <hr/>
            <h6>Plans by Usage</h6>
            <canvas id="chartPlanUsage" class="mb-4"></canvas>
        </div>
    </div>


{% endblock %}

app/request/templates/request/activation.html
{% extends 'request/base.html' %}{% load crispy_forms_tags %}

{% block title %}Activate PartyMan Instance{% endblock %}

{% block content %}
    <h2>Activate PartyMan instance</h2>
    {% crispy form %}
{% endblock %}

app/request/templates/request/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <title>Request PartyMan Instance</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.8/css/bootstrap.min.css"
          integrity="sha512-2bBQCjcnw658Lho4nlXJcc6WkV/UxpE/sAokbXPxQNGqmNdQrWqtw26Ns9kFF/yG792pKR1Sx8/Y1Lf1XN4GKA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
          integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    {% block extrahead %}
    {% endblock %}
</head>
<body>


<nav class="navbar navbar-expand bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'request:landing_page' %}">Partyman</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'request:activation-list' %}">Activation</a>
                {% if user.is_superuser %}
                    <a class="nav-link" href="{% url 'admin:index' %}">Django Admin</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

{% if app_settings.sandbox_mode %}
    <div class="alert alert-warning" role="alert">
        Sandbox mode! Cloudflare and UpCloud functionalities disabled
    </div>
{% endif %}

<div class="container my-4">

    {% block content %}
    {% endblock %}

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.8/js/bootstrap.bundle.min.js"
        integrity="sha512-HvOjJrdwNpDbkGJIG2ZNqDlVqMo77qbs4Me4cah0HoDrfhrbA+8SBlZn1KrvAQw7cILLPFJvdwIgphzQmMm+Pw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>



{% block extrafooter %}
{% endblock %}
</body>

</html>

app/request/templates/request/index.html
{% extends "request/base.html" %}{% load crispy_forms_tags %}
{% block extrahead %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.13/flatpickr.min.css"
          integrity="sha512-MQXduO8IQnJVq1qmySpN87QQkiR1bZHtorbJBD0tzy7/0U9+YIC93QWHeGTEoojMVHWWNkoCp8V6OzVSYrX0oQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.13/themes/dark.min.css"
          integrity="sha512-9j8LE+fuBZgXOsSyiXCw0LmM4LSLIo94AYem4pQzyqlbw5wC4qK2ytHjOLy9pGH3DbvoXawLPuiVfr8gXOKXWw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            flatpickr(".dateinput", {
                locale: {
                    firstDayOfWeek: 1
                }
            })
        })
    </script>
{% endblock %}
{% block content %}

    <h3>Request PartyMan instance</h3>

    {% crispy form %}

{% endblock %}

{% block extrafooter %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.13/flatpickr.min.js"
            integrity="sha512-K/oyQtMXpxI4+K0W7H25UopjM8pzq0yrVdFdG21Fh5dBe91I40pDd9A4lzNlHPHBIP2cwZuoxaUSX0GJSObvGA=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

app/request/templates/request/success.html
{% extends 'request/base.html' %}

{% block content %}

    <h3>Your PartyMan instance has been requested!</h3>
    <p>Thank you for your request. You will receive an email confirmation shortly.</p>
    <p>If you have any questions, please contact our support team.</p>

{% endblock %}